<a href="https://colab.research.google.com/github/vishrutiii/emailSpamdetector/blob/main/emailSpamFiltering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import glob
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string 

In [3]:
from google.colab import files

In [4]:
uploadf = files.upload()

Saving emails.csv to emails.csv


In [7]:
df = pd.read_csv('emails.csv')

In [10]:
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [12]:
df.shape

(5728, 2)

In [13]:
import re
import string
from nltk.tokenize import word_tokenize

In [14]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.


In [18]:
def remove_hyperlink(word):
    return  re.sub(r"http\S+", "", word)

In [17]:
def remove_hyperlink1(word):
    return  re.sub(r"https\S+", "", word)

In [19]:
def to_lower(word):
    result = word.lower()
    return result

In [20]:
def remove_number(word):
    result = re.sub(r'\d+', '', word)
    return result

In [39]:
def remove_sub(word):
  result = word.replace("Subject:", "")
  return result

In [22]:
def remove_whitespace(word):
    result = word.strip()
    return result

In [23]:
def remove_punctuation(word):
    result = word.translate(str.maketrans(dict.fromkeys(string.punctuation)))
    return result

In [24]:
def replace_newline(word):
    return word.replace('\n','')

In [88]:
# def cleaner(sentence):
#     cleaning_utils = [remove_hyperlink,
#                       remove_hyperlink1,
#                       replace_newline,
#                       to_lower,
#                       remove_number,
#                       remove_sub,
#                       remove_punctuation,
#                       remove_whitespace]
#     for i in cleaning_utils:
#         sentence = i(sentence)
#     return sentence

In [66]:
# x = df['text']

In [44]:
# x.shape

(17110,)

In [114]:
# df['text'].head().apply(cleaner)

0    subject naturally irresistible your corporate ...
1    subject the stock trading gunslinger  fanny is...
2    subject unbelievable new homes made easy  im w...
3    subject  color printing special  request addit...
4    subject do not have money  get software cds fr...
Name: text, dtype: object

In [97]:
# xsamp

0    subject naturally irresistible your corporate ...
1    subject the stock trading gunslinger  fanny is...
2    subject unbelievable new homes made easy  im w...
3    subject  color printing special  request addit...
4    subject do not have money  get software cds fr...
Name: text, dtype: object

In [119]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [51]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [120]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [121]:
def cleaner(sentence):
    cleaning_utils = [remove_hyperlink,
                      remove_hyperlink1,
                      replace_newline,
                      to_lower,
                      remove_number,
                      remove_sub,
                      remove_punctuation,
                      remove_whitespace,
                      word_tokenize]
    for i in cleaning_utils:
        sentence = i(sentence)
    return sentence

In [122]:
df['text'].head().apply(cleaner)

0    [subject, naturally, irresistible, your, corpo...
1    [subject, the, stock, trading, gunslinger, fan...
2    [subject, unbelievable, new, homes, made, easy...
3    [subject, color, printing, special, request, a...
4    [subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [100]:
# xsamp

0    [subject, naturally, irresistible, your, corpo...
1    [subject, the, stock, trading, gunslinger, fan...
2    [subject, unbelievable, new, homes, made, easy...
3    [subject, color, printing, special, request, a...
4    [subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [54]:
# def word_stemmer(words):
#     return [stemmer.stem(o) for o in words]

In [55]:
# def word_lemmatizer(words):
#     return [lemmatizer.lemmatize(o) for o in words]

In [56]:
# def clean_token_pipeline(words):
#     cleaning_utils = [word_lemmatizer]
#     for o in cleaning_utils:
#         words = o(words)
#     return words

In [117]:
# df['text'].head().apply(clean_token_pipeline)

0    [S, u, b, j, e, c, t, :,  , n, a, t, u, r, a, ...
1    [S, u, b, j, e, c, t, :,  , t, h, e,  , s, t, ...
2    [S, u, b, j, e, c, t, :,  , u, n, b, e, l, i, ...
3    [S, u, b, j, e, c, t, :,  , 4,  , c, o, l, o, ...
4    [S, u, b, j, e, c, t, :,  , d, o,  , n, o, t, ...
Name: text, dtype: object

0    [subject, naturally, irresistible, your, corpo...
1    [subject, the, stock, trading, gunslinger, fan...
2    [subject, unbelievable, new, home, made, easy,...
3    [subject, color, printing, special, request, a...
4    [subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [69]:
xsamp = [''.join(o) for o in xsamp]

In [76]:
def do_split(word):
  result = word.split()
  return result

In [78]:
# xsamp = df['text'].head().apply(do_split)

In [79]:
# xsamp

0    [Subject:, naturally, irresistible, your, corp...
1    [Subject:, the, stock, trading, gunslinger, fa...
2    [Subject:, unbelievable, new, homes, made, eas...
3    [Subject:, 4, color, printing, special, reques...
4    [Subject:, do, not, have, money, ,, get, softw...
Name: text, dtype: object

splitting


In [125]:
y = df['spam']

In [ ]:
y

In [123]:
from sklearn.feature_extraction.text import CountVectorizer

In [124]:
message_ex = CountVectorizer(analyzer=cleaner).fit_transform(df['text'])

In [128]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(message_ex, y, test_size=0.20, random_state=0)

In [130]:
message_ex.shape

(5728, 33750)

In [131]:
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

In [132]:
def plot_wordcloud(text, mask=None, max_words=200, max_font_size=100, figure_size=(24.0,16.0), 
                   title = None, title_size=40, image_color=False):
    stopwords = set(STOPWORDS)
    more_stopwords = {'one', 'br', 'Po', 'th', 'sayi', 'fo', 'Unknown'}
    stopwords = stopwords.union(more_stopwords)

    wordcloud = WordCloud(background_color='black',
                    stopwords = stopwords,
                    max_words = max_words,
                    max_font_size = max_font_size, 
                    random_state = 42,
                    width=800, 
                    height=400,
                    mask = mask)
    wordcloud.generate(str(text))
    
    plt.figure(figsize=figure_size)
    if image_color:
        image_colors = ImageColorGenerator(mask);
        plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear");
        plt.title(title, fontdict={'size': title_size,  
                                  'verticalalignment': 'bottom'})
    else:
        plt.imshow(wordcloud);
        plt.title(title, fontdict={'size': title_size, 'color': 'black', 
                                  'verticalalignment': 'bottom'})
    plt.axis('off');
    plt.tight_layout()  

In [133]:
spam_train_index = [i for i,o in enumerate(y_train) if o == 1]
non_spam_train_index = [i for i,o in enumerate(y_train) if o == 0]

In [136]:
X_train.shape

(4582, 33750)

In [138]:
# spam_email = np.array(X_train)[spam_train_index]
# non_spam_email = np.array(X_train)[non_spam_train_index]

In [140]:
# plot_wordcloud(spam_email,title = 'Spam Email')

In [140]:
# try plotting w bar graphs

In [144]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

In [146]:
clf = MultinomialNB().fit(X_train, y_train)

In [147]:
print(clf.predict(X_train))

[0 0 1 ... 0 0 0]


In [149]:
print(y_train.values)

[0 0 1 ... 0 0 0]


In [150]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [153]:
pred = clf.predict(X_train)
print('classification report \n')
print(classification_report(y_train, pred))

classification report 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3475
           1       0.99      1.00      0.99      1107

    accuracy                           1.00      4582
   macro avg       0.99      1.00      1.00      4582
weighted avg       1.00      1.00      1.00      4582



In [154]:
print('confusion matrix \n')
print(confusion_matrix(y_train, pred))

confusion matrix 

[[3463   12]
 [   3 1104]]


In [156]:
print('accuracy: \n')
print(accuracy_score(y_train, pred))

accuracy: 

0.9967263203841118


In [157]:
# for x_test
pred1 = clf.predict(X_test)
print('classification report \n')
print(classification_report(y_test, pred1))
print('confusion matrix \n')
print(confusion_matrix(y_test, pred1))
print('accuracy: \n')
print(accuracy_score(y_test, pred1))

classification report 

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       885
           1       0.96      0.99      0.97       261

    accuracy                           0.99      1146
   macro avg       0.98      0.99      0.98      1146
weighted avg       0.99      0.99      0.99      1146

confusion matrix 

[[873  12]
 [  3 258]]
accuracy: 

0.9869109947643979
